---
title: "絵具の科学グラフ"
author: "涌井孝治"
date: "2018年6月22日"
output: html_document
---

[三原色(シアン)](#三原色(シアン))

[三原色(マゼンタ)](#三原色(マゼンタ))

[三原色(イエロー)](#三原色(イエロー))

[原光線の分布(旧図版9-1)](#原光線の分布)

[アニリン黒(旧図版9-2)](#アニリン黒)

[Cイルミナント](#Cイルミナント)

[D~65~イルミナント](#D65イルミナント)

[蛍光ランプD~65~](#蛍光ランプD65)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
```

```{r loadfunc def}
load.spectre <- function(file) {
  read_tsv(file, locale = locale(encoding = "CP932")) %>%
  gather("wavelength", "percent", 3:33) %>%
  mutate("wavelength" = as.integer(substr(wavelength, 1, 3)))
}
```

```{r load, include=FALSE}
spectre <- load.spectre("primary")
pricn <- spectre %>% filter(name == "Primary Cyan")
prima <- spectre %>% filter(name == "Primary Magenta")
priy <- spectre %>% filter(name == "Primary Yellow")
phbys <- spectre %>% filter(name == "HWC PhBYS YA")
qma <- spectre %>% filter(name == "HWC RoV 16") # 旧名Rose Violet
imdy <- spectre %>% filter(name == "HWC ImdYD ZA")
cilluminant <- spectre %>% filter(name == "C")
fl <- spectre %>% filter(name == "fl_d65_JISZ8716")
d65 <- spectre %>% filter(name == "D65")
```

```{r plotfunc def}
plotfunc <- function(d, spar = NULL) {
  g <- d$percent
  plot((40:70)*10, g, ty='n', mgp=c(3,0.5,0), tcl=0.5, las=1, xaxs='i', yaxs='i', font.axis=2, lab=c(3,3,3), xlab='', ylab='', xlim=c(400,700), ylim=c(0,100))
  addline(d, spar)
}
```
```{r addline def}
addline <- function(d, spar = NULL) {
  g <- d$percent
  sp <- smooth.spline((40:70)*10, g, spar = spar)
  pred <- predict(sp, seq(400, 700))
  lines(pred, lwd=4)
  points((40:70)*10, g, pch=19, cex=1.5)
}
```

<a name="三原色(シアン)"></a>
三原色(シアン)

```{r Primary Cyan}
plotfunc(pricn)
```

<a name="三原色(マゼンタ)"></a>
三原色(マゼンタ)

```{r Primary Magenta}
plotfunc(prima)
```

<a name="三原色(イエロー)"></a>
三原色(イエロー)

```{r Primary Yellow}
plotfunc(priy)
```

<a name="原光線の分布"></a>
原光線の分布(全ての波長で100%!)

```{r}
d <- data.frame(percent = rep(99, 31))
plotfunc(d)
```

<a name="アニリン黒"></a>
アニリン黒(全ての波長で0%!)

```{r aniline black}
d <- data.frame(percent = rep(1, 31))
plotfunc(d)
```

<a name="Cイルミナント"></a>
Cイルミナント

旧版図10の標準光のスペクトルはCでもD~65~でもない。通常測色に用いているのはCイルミナントなので、図版もCを採用すべきだろう。

```{r C illuminant}
cilluminant.alt <- cilluminant %>% mutate(percent = percent / max(percent) * 100)
plotfunc(cilluminant.alt)
```

<a name="D65イルミナント"></a>
D~65~イルミナント

```{r D65 illuminant}
d65.alt <- d65 %>% mutate(percent = percent / max(percent) * 100)
plotfunc(d65.alt)
```

<a name="蛍光ランプD65"></a>
蛍光ランプD65(JISZ8716)

同じく、旧版図10の蛍光灯スペクトルと同じものは見当たらなかった。ここではJIS規格のD~65~ランプのスペクトルを採用している。

10nm刻みでは大きなピークが見えなくなっている

```{r FL lamp}
fl.alt <- fl %>% mutate(percent = percent / max(percent) * 100)
plotfunc(fl.alt, spar = 0)
```

カドミウムレモン
カドミウムオレンジ
バーントシエンナ
